### ISSUE TITLE
Tests fail when updating from 4.4.0 to 4.8.0 with: "uninitialized constant Pagy"

### ISSUE THREAD

**Issue by viktorsmari** [davidcelis/api-pagination#104]
We have a rails api with api-pagination + kaminari
When updating gems, and when api-pagination goes to 4.8.0 we get the following error msg:

```
      Failure/Error: @users = paginate(@users)
      
      NameError:
        uninitialized constant Pagy
```

Is api-pagination (wrongly) guessing we use Pagy?

**Comment by davidcelis** [comment]
@viktorsmari This was fixed in a previous PR, but hasn't been deployed yet; I was waiting on a previous PR and advising folks to stay on 4.7 because Pagy was the only addition to 4.8, but since this is the third issue that's been opened about this error (#101, #98, fixed in #99), I'm just going to cut a new release
