### ISSUE TITLE
Suport to Range Pagination

### ISSUE THREAD

**Issue by manoelneto** [davidcelis/api-pagination#34]
Hi, thank you very much for your support in this project. I`m using it in a particular project and like it very very much. 

Thank you.

But I`m missing something in it: range pagination
like in this image bellow.

Do you figure how I can do something like that?

![687474703a2f2f692e696d6775722e636f6d2f4c437172742e676966](https://cloud.githubusercontent.com/assets/2057771/6000638/f3b997ca-aabe-11e4-8ad3-80e4f9956c0a.gif)

this image is from this python module for django https://github.com/jamespacileo/django-pure-pagination

**Comment by davidcelis** [comment]
Hey @manoelneto; api-pagination is just a backend solution for pagination in a RESTful API. It doesn't know anything about (or care about) the frontend, so I'm a little confused by the request. Are you writing a web app on top of an API that uses api-pagination? If that's the case, then what you'd want is Javascript that could handle the `Link`, `Total`, and `Per-Page` headers to construct pagination controls like the image you showed

**Comment by manoelneto** [comment]
You`re right, but parse pages numbers from the Link like url style is,
IMHO, bad.

But talking another feature i`ld like to see, can you return current page
number in response header?

As your gem has only prev, next, first and last page, its quite trick for
me to get current page.

For example, i use angular and your application, with ngRoute to show a
page with a list of posts. So i show buttons based on your response headers
to get first and last url. If i want to know current page, i need to parse
it from curent website url. I think it`s easier to get from response header.

On Mon, Feb 2, 2015 at 2:40 PM, David Celis <notifications@github.com>
wrote:

> Hey @manoelneto <https://github.com/manoelneto>; api-pagination is just a
> backend solution for pagination in a RESTful API. It doesn't know anything
> about (or care about) the frontend, so I'm a little confused by the
> request. Are you writing a web app on top of an API that uses
> api-pagination? If that's the case, then what you'd want is Javascript that
> could handle the Link, Total, and Per-Page headers to construct
> pagination controls like the image you showed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidcelis/api-pagination/issues/34#issuecomment-72500960>
> .
>



-- 
Atenciosamente.

Manoel Quirino Neto

083 81302596 (vivo)
083 96023714 (vivo)

**Comment by davidcelis** [comment]
Hmm, I see the frustration... To be honest I'm not really a fan of adding more headers or links that can be constructed from those already returned. With the way it is now, all the info returned by `api-pagination` is necessary. The `Total`, `Per-Page` and Link headers can tell you everything you need to construct other information (e.g. the number of items on the last page). I'd rather not add something like, say, another Link with a rel of "current" that either the client already knows (because it was just requested) or can be constructed from the "prev" and "next" links

As far as client-side concerns go, there's also a good amount of info out there about how to parse query parameters out of URLs so, if you combine that with something like [this JavaScript snippet](https://gist.github.com/niallo/3109252) to organize the Link headers themselves, I don't think parsing URIs in JS is really unreasonable. I know this isn't the answer you were looking for; sorry!

**Comment by davidcelis** [comment]
One last thought: the Link headers generated by this gem are pretty much the same ones given by the GitHub API (in fact I give a bit more info, as they don't appear to expose a `Total` or `Per-Page` header). They have a nice little guide on how to consume it, though it does use Ruby: https://developer.github.com/guides/traversing-with-pagination/

**Comment by manoelneto** [comment]
Not a problem man. You did a great work.

Thank you. 

I think that it`s really not necessary to return current page, as you said, just because i requested. but if i need to get more information, I can make a fork of your repo.

Again, thank you
