### ISSUE TITLE
Add option to turn off total count

### ISSUE THREAD

**Issue by aaronchi** [davidcelis/api-pagination#35]
I ahve an issue with an api I'm working on that queries against a collection wit millions of records. I want to return the Link header but not the total to avoid the extra query call for total count.

It would be nice if this was a configurable option.

**Comment by davidcelis** [comment]
Hmm... This seems reasonable but I feel like I need to ask: how long does the `SELECT COUNT(*) ...` query take for your collection? Is it really enough that generating the “Total” header is a noticeable performance loss?

**Comment by aaronchi** [comment]
On the one query that's looking at 2.7M records, it takes almost a minute for the api call to complete.

I'm not sure it's a big concern for anyone else, so I just hacked something together here:
https://github.com/bitium/api-pagination/commit/dcdf526a283f885a9cebfea500949c7438c1d87b

Basically allows paginate to take a skip_total option and modifies the way the data is returned. Can probably be improved.

**Comment by jarinudom** [comment]
You could try https://github.com/desktoppr/cached_counts also

**Comment by joevandyk** [comment]
I'd like this as well.

**Comment by Phifo** [comment]
is this already implemented? I set `config.include_total = false` but the pagination is still querying the count.

**Comment by davidcelis** [comment]
@Phifo It looks like the patch I included only skips a query for calculating the `Total` header. But since the number of records is still necessary for calculating the last page… It's gonna execute a `COUNT` query regardless 😞

Unfortunately, at this point I think this is a WONTFIX for me. I'd rather not support this sort of edge case in the api-pagination gem and need to implement functionality that prevents what I feel like are all of the necessary links in the `Link` header. I'll likely deprecate the `config.include_total` patch before v5.0 as well because of this.

I strongly recommend looking into ways to speed up query performance on that table instead. I know that's not a great answer. Sorry!

**Comment by joevandyk** [comment]
I think it's a pretty common thing to paginate across large result sets, I wouldn't consider it an edge case.

**Comment by davidcelis** [comment]
"Edge case" probably wasn't the best phrase, but what it comes down to is that the case of paginating across a large result set where the `COUNT` query takes unreasonably long is not a case I'd like api-pagination to try to deal with… In the case of this gem, it means leaving out the `Total` header and the link to the `last` page in the `Link` header. I was _okay_ with the first result. I'm not really okay with the latter one.

**Comment by joevandyk** [comment]
Why are you not ok with skipping the `last` header? I am. :)

**Comment by Phifo** [comment]
@davidcelis your answer makes a lot of sense, I should find a way to speed up the count query. Leaving out the last page in the link header will not follow the standard.
