### ISSUE TITLE
4.5.0: NoMethodError: undefined method `paginate'

### ISSUE THREAD

**Issue by jpaas** [davidcelis/api-pagination#70]
I tried upgrading from 4.4.0 to 4.5.0 and the paginate method could not be found on my controllers any more. Downgraded and it works fine again.

**Comment by davidcelis** [comment]
@jpaas I'm guessing you're using Rails 5, but your API controllers inherit from `ActionController::Base` instead of `ActionController::API`? 4.5.0 introduced a change with Rails 5 support that includes the pagination module only where it detects it should be necessary. It used to end up being included in both `ActionController::Base` and `ActionController::API` but, in the interest of not polluting controllers unnecessarily, it only gets included automatically into `ActionController::API`.

If for some reason you can't update your controllers to inherit from `ActionController::API`, you can always include the `Rails::Pagination` module into your API's `ApplicationController` manually.

**Comment by jpaas** [comment]
You are absolutely correct sir! Thanks for the super speedy response. Might be a good addition to the release notes ;)

**Comment by davidcelis** [comment]
That's a great idea, thanks @jpaas!
